"""
Report formatters for different output formats.

Provides formatters for JSON, Markdown, and rich table output.
"""

import json
from abc import ABC, abstractmethod
from datetime import datetime
from typing import Any

from dhm.core.models import (
    DependencyReport,
    HealthGrade,
    MaintenanceStatus,
)


class Formatter(ABC):
    """Abstract base class for report formatters."""

    @abstractmethod
    def format(self, reports: list[DependencyReport]) -> str:
        """Format a list of dependency reports.

        Args:
            reports: List of DependencyReport objects.

        Returns:
            Formatted string output.
        """
        pass

    @property
    @abstractmethod
    def file_extension(self) -> str:
        """Return the appropriate file extension for this format."""
        pass


class JSONFormatter(Formatter):
    """Format reports as JSON."""

    def __init__(self, indent: int = 2, include_metadata: bool = True):
        """Initialize the JSON formatter.

        Args:
            indent: JSON indentation level.
            include_metadata: Whether to include report metadata.
        """
        self.indent = indent
        self.include_metadata = include_metadata

    def format(self, reports: list[DependencyReport]) -> str:
        """Format reports as JSON string.

        Args:
            reports: List of DependencyReport objects.

        Returns:
            JSON string.
        """
        data: dict[str, Any] = {
            "dependencies": [report.to_dict() for report in reports],
        }

        if self.include_metadata:
            data["metadata"] = {
                "generated_at": datetime.utcnow().isoformat(),
                "total_packages": len(reports),
                "summary": self._generate_summary(reports),
            }

        return json.dumps(data, indent=self.indent, default=str)

    def _generate_summary(self, reports: list[DependencyReport]) -> dict[str, Any]:
        """Generate summary statistics for reports."""
        grades = {"A": 0, "B": 0, "C": 0, "D": 0, "F": 0}
        total_vulns = 0
        unmaintained = 0

        for report in reports:
            grades[report.health.grade.value] += 1
            total_vulns += len(report.health.vulnerabilities)
            if report.health.maintenance_status.is_concerning:
                unmaintained += 1

        return {
            "grades": grades,
            "healthy_count": grades["A"] + grades["B"],
            "concerning_count": grades["D"] + grades["F"],
            "total_vulnerabilities": total_vulns,
            "unmaintained_count": unmaintained,
        }

    @property
    def file_extension(self) -> str:
        return ".json"


class MarkdownFormatter(Formatter):
    """Format reports as Markdown."""

    def __init__(self, include_alternatives: bool = True):
        """Initialize the Markdown formatter.

        Args:
            include_alternatives: Whether to include alternative package suggestions.
        """
        self.include_alternatives = include_alternatives

    def format(self, reports: list[DependencyReport]) -> str:
        """Format reports as Markdown string.

        Args:
            reports: List of DependencyReport objects.

        Returns:
            Markdown string.
        """
        lines = ["# Dependency Health Report", ""]

        # Summary section
        lines.extend(self._format_summary(reports))

        # Critical issues - vulnerabilities
        critical = [r for r in reports if r.health.vulnerabilities]
        if critical:
            lines.extend(self._format_vulnerabilities(critical))

        # Unmaintained packages
        unmaintained = [
            r for r in reports
            if r.health.maintenance_status.is_concerning
        ]
        if unmaintained:
            lines.extend(self._format_unmaintained(unmaintained))

        # Full breakdown table
        lines.extend(self._format_full_table(reports))

        # Footer
        lines.extend([
            "",
            "---",
            f"*Generated by Dependency Health Monitor on {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}*",
        ])

        return "\n".join(lines)

    def _format_summary(self, reports: list[DependencyReport]) -> list[str]:
        """Format the summary section."""
        total = len(reports)
        healthy = sum(1 for r in reports if r.health.grade in (HealthGrade.A, HealthGrade.B))
        concerning = sum(1 for r in reports if r.health.grade in (HealthGrade.D, HealthGrade.F))
        with_vulns = sum(1 for r in reports if r.health.vulnerabilities)

        return [
            "## Summary",
            "",
            f"- **Total Dependencies:** {total}",
            f"- **Healthy (A/B):** {healthy}",
            f"- **Concerning (D/F):** {concerning}",
            f"- **With Vulnerabilities:** {with_vulns}",
            "",
        ]

    def _format_vulnerabilities(self, reports: list[DependencyReport]) -> list[str]:
        """Format the vulnerabilities section."""
        lines = ["## Security Vulnerabilities", ""]

        for report in reports:
            lines.append(f"### {report.package.name}")
            if report.package.version:
                lines.append(f"*Version: {report.package.version}*")
            lines.append("")

            for vuln in report.health.vulnerabilities:
                lines.append(f"- **{vuln.id}** ({vuln.severity.value}): {vuln.title}")
                if vuln.fixed_version:
                    lines.append(f"  - Fixed in: `{vuln.fixed_version}`")
            lines.append("")

        return lines

    def _format_unmaintained(self, reports: list[DependencyReport]) -> list[str]:
        """Format the unmaintained packages section."""
        lines = ["## Unmaintained Packages", ""]

        for report in reports:
            status = report.health.maintenance_status.value
            lines.append(f"- **{report.package.name}** - {status}")

            if self.include_alternatives and report.alternatives:
                alt = report.alternatives[0]
                lines.append(
                    f"  - Consider: `{alt.package.name}` (score: {alt.health_score:.0f})"
                )

        lines.append("")
        return lines

    def _format_full_table(self, reports: list[DependencyReport]) -> list[str]:
        """Format the full dependency table."""
        lines = [
            "## All Dependencies",
            "",
            "| Package | Version | Grade | Security | Maintenance | Status |",
            "|---------|---------|-------|----------|-------------|--------|",
        ]

        # Sort by overall score (lowest first to highlight problems)
        sorted_reports = sorted(reports, key=lambda r: r.health.overall)

        for report in sorted_reports:
            pkg = report.package
            health = report.health

            lines.append(
                f"| {pkg.name} | {pkg.version or '-'} | {health.grade.value} | "
                f"{health.security_score:.0f} | {health.maintenance_score:.0f} | "
                f"{health.maintenance_status.value} |"
            )

        lines.append("")
        return lines

    @property
    def file_extension(self) -> str:
        return ".md"


class TableFormatter(Formatter):
    """Format reports as plain text tables.

    This is a simple text-based table format. For rich terminal output,
    use the CLI module which uses the Rich library.
    """

    def format(self, reports: list[DependencyReport]) -> str:
        """Format reports as a text table.

        Args:
            reports: List of DependencyReport objects.

        Returns:
            Plain text table string.
        """
        if not reports:
            return "No dependencies found."

        # Column definitions
        columns = [
            ("Package", 30),
            ("Version", 12),
            ("Grade", 5),
            ("Security", 8),
            ("Maint.", 8),
            ("Status", 12),
            ("Issues", 20),
        ]

        # Header
        header = " | ".join(
            name.ljust(width) for name, width in columns
        )
        separator = "-+-".join("-" * width for _, width in columns)

        lines = [
            "Dependency Health Report",
            "=" * len(header),
            "",
            header,
            separator,
        ]

        # Sort by overall score
        sorted_reports = sorted(reports, key=lambda r: r.health.overall)

        for report in sorted_reports:
            pkg = report.package
            health = report.health

            # Build issues string
            issues = []
            if health.vulnerabilities:
                issues.append(f"{len(health.vulnerabilities)} vulns")
            if health.maintenance_status.is_concerning:
                issues.append(health.maintenance_status.value)
            issues_str = ", ".join(issues) if issues else "OK"

            row = [
                pkg.name[:30].ljust(30),
                (pkg.version or "-")[:12].ljust(12),
                health.grade.value.ljust(5),
                f"{health.security_score:.0f}".ljust(8),
                f"{health.maintenance_score:.0f}".ljust(8),
                health.maintenance_status.value[:12].ljust(12),
                issues_str[:20].ljust(20),
            ]

            lines.append(" | ".join(row))

        # Summary
        lines.extend([
            "",
            separator,
            f"Total: {len(reports)} packages",
        ])

        return "\n".join(lines)

    @property
    def file_extension(self) -> str:
        return ".txt"
